services:
  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    container_name: soketi
    restart: unless-stopped
    ports:
      - "6001:6001"
      - "9601:9601"
    volumes:
      - /etc/certs:/etc/certs:ro
    environment:
      SOKETI_DEBUG: "0"
      SOKETI_DEFAULT_APP_ID: "${SOKETI_APP_ID}"
      SOKETI_DEFAULT_APP_KEY: "${SOKETI_APP_KEY}"
      SOKETI_DEFAULT_APP_SECRET: "${SOKETI_APP_SECRET}"
      SOKETI_DEFAULT_APP_MAX_CONNS: "500"
      SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: "false"
      SOKETI_SSL_CERT: "/etc/certs/fullchain.pem"
      SOKETI_SSL_KEY: "/etc/certs/santacasa_org_br.key"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9601/usage"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
